export const LOGIN_EMAIL_REQUIRED = 'LOGIN_EMAIL_REQUIRED';
export const LOGIN_PASSWORD_REQUIRED = 'LOGIN_PASSWORD_REQUIRED';
export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';
export const FETCHING = 'FETCHING';
export const LOGIN_RESET = 'LOGIN_RESET';

export const CREATE_AC_NAME_REQUIRED = 'CREATE_AC_NAME_REQUIRED';
export const CREATE_AC_EMAIL_REQUIRED = 'CREATE_AC_EMAIL_REQUIRED';
export const CREATE_AC_PASSWORD_REQUIRED = 'CREATE_AC_PASSWORD_REQUIRED';
export const CREATE_AC_CF_PASSWORD_REQUIRED = 'CREATE_AC_CF_PASSWORD_REQUIRED';
export const CREATE_AC_PHONE_REQUIRED = 'CREATE_AC_PHONE_REQUIRED';
export const CREATE_AC_NAME = 'CREATE_AC_NAME';
export const CREATE_AC_EMAIL = 'CREATE_AC_EMAIL';
export const CREATE_AC_PASSWORD = 'CREATE_AC_PASSWORD';
export const CREATE_AC_PHONE = 'CREATE_AC_PHONE';
export const CREATE_AC_CF_PASSWORD = 'CREATE_AC_CF_PASSWORD';
export const CREATE_AC_RESET = 'CREATE_AC_RESET';
